### ISSUE TITLE
Xcode 10, update by Carthage - Task failed with exit code 65:

### ISSUE THREAD

**Issue by dillidon** [SoySauceLab/CollectionKit#103]
Carthage:
...
This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details:
...

SpaceProvider.swift:14:10: error: Identifier Name Violation: Enum element name should only contain alphanumeric characters: 'absolute(_:)' (identifier_name)

SimpleViewProvider.swift:16:10: error: Identifier Name Violation: Enum element name should only contain alphanumeric characters: 'absolute(_:)' (identifier_name)

How can I solve this?

**Comment by lkzhao** [comment]
This is a `swiftlint` issue:
https://github.com/realm/SwiftLint/issues/2231

update your swiftlint should fix it.

**Comment by lkzhao** [comment]
will close this for now. please reopen if this is still an issue.
