### ISSUE TITLE
[Help] A usage help

### ISSUE THREAD

**Issue by wakaryry** [SoySauceLab/CollectionKit#106]
I want to realize a scrollable view which has multi-parts. 
As marked:
<img width="1080" alt="default" src="https://user-images.githubusercontent.com/7576559/46751855-4c593e80-ccee-11e8-9ff5-9d225dfda203.png">

The whole page is scrollable. `Part 1` is fixed height. `Part 2` has a fixed-height tab bar and dynamic-height content.

When scrolling, if `Part 1` is still in visible screen, we can scroll the whole page. If `Part 1` is not in visible screen, when scrolling, the `Part 2` can scroll, thus we could see more and load more content for `Part 2`.

And we could scroll left/right for `Part 2` to switch to another tab and content.

How could I realize it with `CollectionKit`?

More states:
### It could scroll for whole page:
![default](https://user-images.githubusercontent.com/7576559/46752881-e02c0a00-ccf0-11e8-90f2-53e8e25c9bdf.png)

### It could scroll for `Part 2`:
![default](https://user-images.githubusercontent.com/7576559/46752926-fafe7e80-ccf0-11e8-8297-02febf2ec5a3.png)

If `Part 2` with no tabs, I could handle it using a composed provider(SimpleView + Basic or two Basic) with sections. And stick the section header.

But if `Part 2` with tabs, I want to use different controller to handle content for different tab.
How could I make it possible with `CollectionKit`.

Actually I do not kown how to realize it with any scroll view.

What I think:
`Part 1` and `Part 2` are all `SimpleViewProvider ` content, then I save all the `Part 2` cells' height, and assign its' total as `Part 2`'s provider's height. But the problem is the content of `Part 2` is dynamic, the total height changes when load more. I need to reset provider's height. 

Thanks for any help/solution!

**Comment by lkzhao** [comment]
If you don't need horizontal scrolling function within the second part, then you can just use a single ComposedProvider, with the following sections:

1. simple view provider for `part 1`
2. simple view provider for `part 2 tab control`
3. basic provider for second section.

And when user interact with the tab control. just swap your 3rd section with another basic provider.

**Comment by wakaryry** [comment]
Thanks for the solution of non-horizontal scrolling.
My horizontal scrolling function is needed within the second part. And the `tab control` could be sticky.
I want to use other controllers with CollectionView to control the `part 2 content`.
What I do is to enable/disable the scroll behavior to control scroll gesture priorities.

**Comment by wakaryry** [comment]
It's solved.

### My needs
#### UI Design
a header view (`Part 1`), a tab controls view (`Part 2`), scrollable view (`Part 3`).
#### Function Design
All the page is scrollable. When `Part 1` is on the visible screen, we scroll the all page. When `Part 1` is not on the visible screen, we stick the tab controls,  i.e. `Part 2`. And `Part 3` becomes scrollable. The detail shows in the issue description.

### Solution
#### 1. ScrollView container and Equal-height blank token view for CollectionView
For the controller of the page, we add a UIScrollView as the content view. 
We add all the tab controls' content (`Part 3`) as subviews of the scrollView.
For all the `Part 3` views, the point is they all have a equal height blank view, which is equal-height to the header view `Part 1`. 
```swift
        self.view.addsubview(scrollView)
        let headV = UIView(frame: CGRect(x: 0, y: 0, width: 0, height: Headerheight))
        let vProvider = SimpleViewProvider(
            identifier: nil,
            views: [headV],
            sizeStrategy: (width: .fill, height: .absolute(Headerheight)),
            layout: FlowLayout()
        )
     
        let data = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
        let aProvider = BasicProvider(
            identifier: nil,
            dataSource: ArrayDataSource(data: data),
            viewSource: ClosureViewSource(viewUpdater: { (label: UILabel, number, index) in
                label.text = "--\(number)--"
            }),
            sizeSource: { (_, _, _) -> CGSize in
                return CGSize(width: self.view.bounds.width, height: 56)
        },
            layout: FlowLayout(),
            animator: nil) { (tapContext) in
                
        }
        let cv1 = CollectionView()
        cv1.provider = ComposedProvider(identifier: nil, layout: FlowLayout(), animator: nil, sections: [vProvider, aProvider])
        
        scrollV.addSubview(cv1)
        // other collectionviews: cv2, cv3...
```
#### 2. Real header view `Part 1` and `Part 2`
The point is that the `Part 1` and `Part 2` is not added into scrollView's subviews, it's subviews of view of the controller.
```swift
self.view.addSubview(headView)
headView.addSubview(Part1)
headView.addSubview(Part2)
```

#### 3. Delegate UIScrollView's delegate. Connect `Part 2` and `Part 3`
Since all `Part 3` are in a scroll view, we could use `contentOffset.x` for switching b/w tabs. The scroll view is pageable.
```swift
    func scrollViewDidEndDecelerating(_ scrollView: UIScrollView) {
        if scrollView == self.scrollView {
            let contentOffsetX = scrollView.contentOffset.x
            let pageNum = contentOffsetX / self.view.bounds.width + 0.5
            // the titlebar is `Part 2`： tab controls
            self.titleBar.selectedIndex = Int(pageNum)
        }
    }
```

#### 4. Delegate UIScrollView's delegate. Enable/Disable the scrollView's scrollable.
We should delegate all the `scrollable view`, including the `CollectionView`.
```swift
scrollView.delegate = self
cv1.delegate = self
cv2.delegate = self
// ......
```
**The HeaderHeight below is just height of `Part 1`**
```swift
    func scrollViewDidScroll(_ scrollView: UIScrollView) {
        if scrollView == self.scrollView || scrollView.window == nil {
            return
        }
        
        let offsetY = scrollView.contentOffset.y
        var originY: CGFloat = 0
        var otherOffsetY: CGFloat = 0
        
        if offsetY <= Headerheight {
            originY = -offsetY
            if offsetY < 0 {
                otherOffsetY = 0
            } else {
                otherOffsetY = offsetY
            }
        } else {
            originY = -Headerheight
            otherOffsetY = Headerheight
        }
        
        var f = self.headerView.frame
        f.origin = CGPoint(x: 0, y: originY)
        self.headerView.frame = f
        
        print("Items Count: \(self.titleBar.items.count)")
        for i in 0..<self.titleBar.items.count {
            if i != self.titleBar.selectedIndex {
                let cv = self.scrollView.subviews[i] as! CollectionView
                let offset = CGPoint(x: 0, y: otherOffsetY)
                if cv.contentOffset.y < Headerheight || offset.y < Headerheight {
                    cv.setContentOffset(offset, animated: false)
                    self.scrollView.offset = offset
                }
            }
        }
    }
```

#### 5. Enable/Disable scroll
The scrollView we used to contain all other scrollable views is a subClass of `HitTestScrollView`.

```swift
import UIKit

let HeaderViewHeight: CGFloat = 200.0

class HitTestScrollView: UIScrollView {
    
    var offset: CGPoint = .zero
    
    override init(frame: CGRect) {
        super.init(frame: frame)
        
        clipsToBounds = false
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        
        clipsToBounds = false
    }
    
    override func hitTest(_ point: CGPoint, with event: UIEvent?) -> UIView? {
        var view = super.hitTest(point, with: event)
        let isHitHead = point.y < (HeaderViewHeight - self.offset.y)
        
        if isHitHead || view == nil {
            self.isScrollEnabled = false
            if view == nil {
                print("view == nil")
                for sub in self.subviews {
                    if sub.frame.origin.x == self.contentOffset.x {
                        view = sub
                    }
                }
            }
            return view
        } else {
            self.isScrollEnabled = true
            return view
        }
    }
}

```

Thanks for all the help.
