### ISSUE TITLE
can't run the demo project 

### ISSUE THREAD

**Issue by MIyulong** [SoySauceLab/CollectionKit#112]
![image](https://user-images.githubusercontent.com/8175565/48530191-93c88100-e8d1-11e8-8ab6-21b15d2b8845.png)
what's the problem？ , running the 'pod update', then i get this while run the CollectionKitExamples.xcworkspace

**Comment by lkzhao** [comment]
Should be fine now. Example project's swift version was set to swift 4.0. while one of the dependency is already updated to swift 4.2.
