### ISSUE TITLE
layout problem

### ISSUE THREAD

**Issue by CoderMaurice** [SoySauceLab/CollectionKit#114]
Hi there,

Collectionkit is great, I like it very much, but I have a problem.

Collectionview in this page is vertical and the size is fixed, but the blue area is horizontally slidable. Can I use one Collectionview to complete it?

![12333333](https://user-images.githubusercontent.com/22311615/48699750-26945300-ec25-11e8-95ee-b64da8a6ee47.jpg)

**Comment by casperzandbergenyaacomm** [comment]
If you want your blue cells to move independently of the other cells you need a second scroll view. You can use a nested CollectionView to still have the the whole page scroll as one.

```
var blueCollectionView = CollectionView()
blueCollectionView.provider = // blue cells

var blueProvider = SimpleViewProvider(
    views: [blueCollectionView],
    sizeStrategy: (.fill, .absolute(200))
)

// main provider
var provider = ComposedProvider(
    sections: [redProvider, blueProvider, greenProvider]
)
```

As shown in [this example](https://github.com/SoySauceLab/CollectionKit/tree/master/Examples/CollectionKitExamples/AnimatorExample).

**Comment by CoderMaurice** [comment]
@casperzandbergenyaacomm Thanks for your reply, I will use two CollectionView to complete it.
