### ISSUE TITLE
How to display placeholders whenever the view has no content to display

### ISSUE THREAD

**Issue by coderflower** [SoySauceLab/CollectionKit#115]

**Comment by lkzhao** [comment]
just use `EmptyStateProvider`

```swift
        let dataSource = ArrayDataSource(data: [0, 1, 2, 4])
        let provider = BasicProvider(
          dataSource: dataSource,
          viewSource: { (label: UILabel, data: Int, index: Int) in },
          sizeSource: { (index: Int, data: Int, collectionSize: CGSize) -> CGSize in
            return CGSize(width: 50, height: 50)
        })
        let emptyLabel = UILabel()
        emptyLabel.text = "Empty Label"
        let emptyProvider = EmptyStateProvider(emptyStateView: emptyLabel, content: provider)
        collectionView.provider = emptyProvider
```

when ever dataSource's data becomes empty. the emptyLabel will be displayed

**Comment by coderflower** [comment]
> 只是用 `EmptyStateProvider`
> 
> ```swift
>         让的dataSource =  ArrayDataSource（数据：[ 0，1，2，4 ]）
>          让提供商=  BasicProvider（
>            数据源：数据源，
>            viewSource：{（标签：的UILabel，数据：诠释，指数：诠释）在 }，
>            sizeSource：{（索引：Int，数据：Int，collectionSize：CGSize）- > CGSize 在
>             返回 CGSize（宽度：50，高度：50）
>         }）
>         let emptyLabel =  UILabel（）
>         emptyLabel。text  =  “ Empty Label ”
>         让 emptyProvider =  EmptyStateProvider（emptyStateView：emptyLabel，content：provider）
>         的CollectionView。provider  = emptyProvider
> ```
> 
> 当dataSource的数据变空时。将显示emptyLabel

thank you! this perfect~

**Comment by lkzhao** [comment]
will close this for now. please reopen if this is still an issue.
