### ISSUE TITLE
Can You help with this issue layout: 

### ISSUE THREAD

**Issue by archercod** [SoySauceLab/CollectionKit#125]
<img width="1090" alt="zrzut ekranu 2019-01-17 o 16 11 27" src="https://user-images.githubusercontent.com/23321310/51329261-72247b00-1a75-11e9-8d56-9cf1928c9637.png">

**Comment by casperzandbergenyaacomm** [comment]
Can you post the code for creating the provider. The screenshot only shows half.

**Comment by archercod** [comment]
Now I have other error

<img width="982" alt="zrzut ekranu 2019-01-18 o 12 51 18" src="https://user-images.githubusercontent.com/23321310/51385510-c7b56200-1b1f-11e9-8d0d-f08b76c9a59d.png">

**Comment by Banck** [comment]
@archercod Hello!
You have to replace `BasicProvider(...)` to `BasicProvider<PromocodeItem, RoundedCardWrapperView>(...)`

**Comment by casperzandbergenyaacomm** [comment]
Ok so the error message is pretty useless in this case. This happens a lot though and I always solve it by manually checking where the error is. 

The error tells you it doesn't know what Data is so we have to check all parts where Data is used.

First, datasource is very simple and we can see it uses the right type so this isnt it. 

Then viewSource and tapHandler are quite complex and use parts of both View and Data that I can't see so there could be something wrong in either of these. To check this just comment all the code in the completion block (if the compiler complains about it being empty just add a print("")). 

If the error isnt there when either viewSource or tapHandler are commented out you know that the error was in the commented block. 

It's too bad Xcode doesn't help you better with this but you can just manually find the error the way I described.

**Comment by archercod** [comment]
Thank You guys! It's work
