### ISSUE TITLE
Is pinterest (masonry) layout currently possible?

### ISSUE THREAD

**Issue by sjmueller** [SoySauceLab/CollectionKit#133]
Is pinterest style layout currently possible with CollectionKit?

![image](https://user-images.githubusercontent.com/29085/56487936-b3bc2c00-6491-11e9-8493-bb89c4f00a92.png)

Most of the examples I've seen have cells with the same height/position within each row.

**Comment by Banck** [comment]
Hello!
Seems, you are looking for WaterfallLayout, which is in-built layout in CollectionKit.

**Comment by sjmueller** [comment]
Thanks for the quick answer, @Banck! I will check out Waterfall Layout this weekend, and close the issue if it is indeed the same concept.

**Comment by lucoxlee** [comment]
i am also looking for WaterfallLayout

**Comment by JonyFang** [comment]
WaterfallLayout is in-built layout in CollectionKit.
