### ISSUE TITLE
How can scroll to the selected item？(怎样才能滚动到所选项目)

### ISSUE THREAD

**Issue by wwdc14yh** [SoySauceLab/CollectionKit#138]
E.g`scrollToRow(at indexPath: IndexPath, at scrollPosition: UITableView.ScrollPosition, animated: Bool)`
例如`scrollToRow(at indexPath: IndexPath, at scrollPosition: UITableView.ScrollPosition, animated: Bool)`

What should I do on `CollectionKit`?
我在`CollectionKit`上应该如何做？

Thank you very much for this open source library!
非常感谢这个开源库！

**Comment by Amzd** [comment]
First get the items index. I usually do something like `provider.dataSource.data.firstIndex { ... }`

Then:
```
if var frame = collectionView.frame(at: indexForItem) {
  collectionView.scrollRectToVisible(frame, animated: true)
}
```

**Comment by wwdc14yh** [comment]
Thank you very much for your answer, but still have questions.
`collectionView.frame(at: indexForItem)`
I didn't find the `frame(at:XX)` method in the `CollectionView` class.
Can you elaborate on this?
Thanks again!

**Comment by Amzd** [comment]
Ah you are right, this must be a function I added myself. I’m not at work so I don’t know my exact implementation but if I remember correctly it just returns the flattenedProvider.frame(at:)

**Comment by wwdc14yh** [comment]
Thank you solve my problem 👍
