### ISSUE TITLE
Demo app failed to build as lack of YetAnotherAnimationLibrary.framework

### ISSUE THREAD

**Issue by tomisacat** [SoySauceLab/CollectionKit#35]
Example target link binary with library`YetAnotherAnimationLibrary.framework`, which is not existed in the project.

**Comment by lkzhao** [comment]
For now, run `carthage install`.
I will update the project soon to checkin the Carthage folder.

**Comment by lkzhao** [comment]
Should be ok now. Checkout the latest master.
