### ISSUE TITLE
CocoaPods can't work

### ISSUE THREAD

**Issue by Wrapperss** [SoySauceLab/CollectionKit#37]
build in Xcode9, pod-version:1.3.1, it has errors

**Comment by lkzhao** [comment]
what kind of error are you getting

**Comment by liuyaxun** [comment]
What's your collectionkit version ？The latest version is 1.2.0 , you can pod update to get it

**Comment by Wrapperss** [comment]
![2017-12-26 2 07 55](https://user-images.githubusercontent.com/16930988/34348538-66ca76d4-ea46-11e7-8f01-ff8798d2b6c7.png)
Is there something wrong with my operation

**Comment by lkzhao** [comment]
@Wrapperss Thats really weird. I have never seen these errors. Can you try updating to the latest CollectionKit, clean your project, and build again?

**Comment by Wrapperss** [comment]
I find it because I am not the latest version  😅thank you for your help!😊
