### ISSUE TITLE
Can't run the project

### ISSUE THREAD

**Issue by Asher1000** [SoySauceLab/CollectionKit#40]
Can you please explain in steps how to run the project using cocoapods or with direct download ?

1.I download the project zip and open it
2.opened CollectionKit.xcodeproj
3.build "CollectionKit"
4. now what ?

I'm objective-c developer and will be nice to run the samples in simple step.
Thanks.

**Comment by Sunnyyoung** [comment]
@Asher1000 Please ensure that you have installed the [Carthage](https://github.com/Carthage/Carthage) and run `carthage build --platform ios`.

**Comment by Asher1000** [comment]
it's the only way ?

**Comment by Sunnyyoung** [comment]
@Asher1000 If you want to run demo, just clone the project and run the `CollectionKitExample` target.

![image](https://user-images.githubusercontent.com/5926284/34326952-7a4410ca-e8f3-11e7-8cbe-254a20a7a7be.png)

**Comment by Asher1000** [comment]
I did this already.
but it gave me an error :
//Library/Developer/Xcode/DerivedData/CollectionKit-bznxdajllusotjbllhxvvwlznvia/Build/Intermediates.noindex/CollectionKit.build/Debug-iphoneos/CollectionKitExample.build/Script-B19D64D11F23E3BF00D02FDB.sh: line 2: /usr/local/bin/carthage: No such file or directory

**Comment by Sunnyyoung** [comment]
@Asher1000 Alright, try this one: delete carthage build phases.

![image](https://user-images.githubusercontent.com/5926284/34327143-f9838de4-e8f7-11e7-9d4d-63a4ad932908.png)

**Comment by Asher1000** [comment]
Thanks for your help.

Now it's compile and run, but crush in the device with :
dyld: Library not loaded: @rpath/YetAnotherAnimationLibrary.framework/YetAnotherAnimationLibrary
  Referenced from: /var/containers/Bundle/Application/063B9DA7-4864-4CD0-A548-EC2287AD239E/CollectionKitExample.app/CollectionKitExample
  Reason: image not found

**Comment by Sunnyyoung** [comment]
😂 Oh I see, I forget this steps: 

1. Add `YetAnotherAnimationLibrary` to the embedded binaries.
2. Remove the duplicate one from Linked Frameworks.

![image](https://user-images.githubusercontent.com/5926284/34327219-d1e09974-e8f9-11e7-966a-dffb0a152233.png)

BTW, it is recommended that you should install the Carthage, which can save you much time :)

**Comment by Asher1000** [comment]
Now it's working ! Thanks ! ( amazing sample)

About the Carthage, I never needed to use this.

Always used cocoapods and that enough for me. I "hate" to use to many tools.

So now, I want to use it in new project (in the future..)
I can't use cocoapods ? or the only way is Carthage ?

I also saw other libraries you made, you did very cool job. this is what I called programmer artist.

**Comment by Sunnyyoung** [comment]
@Asher1000 Haha, you're welcome.
You can use this framework with cocoapods (I'm using now).

**Comment by Asher1000** [comment]
For others, I think you can add more details about the cocoapods likes this 
( on your project I did not see it, and I thought maybe it can not be download with cocoapods, this what confused me) :
To integrate AFNetworking into your Xcode project using CocoaPods, specify it in your Podfile:

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'TargetName' do
pod 'AFNetworking', '~> 3.0'
end
Then, run the following command:

$ pod install

**Comment by lkzhao** [comment]
@Asher1000 you are right, this is very confusing to new comers. I will remove the Carthage dependency for the sample project and include some guides on the readme. Btw thank you @Sunnyyoung for looking into this.
