### ISSUE TITLE
How can I make "section" header?

### ISSUE THREAD

**Issue by alexanderkhitev** [SoySauceLab/CollectionKit#42]
Hello! Thanks for the wonderful framework! I looked at the demo project and read the documentation, but I did not find the mention of "section" headers anywhere. I understand that on providers they replace sections (and do much more), but is it possible to do "section" header out of the box? Thank you.

**Comment by lkzhao** [comment]
You can do so by composing a header with its content together. 

```swift
let section1 = CollectionComposer(
    LabelCollectionProvider(text: "Section Header", font: .boldSystemFont(ofSize: 38)),
    section1ContentProvider,
)
let section2 = CollectionComposer(
    ViewCollectionProvider(section2HeaderView, sizeStrategy: (.fill, .absolute(44))),
    section2ContentProvider,
)
collectionView.provider = CollectionComposer(section1, section2)
```

**Comment by alexanderkhitev** [comment]
@lkzhao ok, thanks. I'll try

**Comment by lkzhao** [comment]
Coming in v2.0 there will also be a `ComposedHeaderProvider` which allows you to specify a `viewProvider` for each section header.

**Comment by lkzhao** [comment]
v2.0 is released. 
Checkout the example project for the header example. It also support sticky header.
