### ISSUE TITLE
Enhance performence with DataProvider

### ISSUE THREAD

**Issue by Maru-zhang** [SoySauceLab/CollectionKit#43]
Maybe the class like ArrayDataProvider should use ContiguousArray instead of Array. When
Element type is a class or @objc protocoll, it would be more predictable performance.

**Comment by Maru-zhang** [comment]
Maybe the class like `ArrayDataProvider` should use `ContiguousArray` instead of `Array`. When 
Element type is a class or @objc protocoll, it would be more predictable performance.

**Comment by lkzhao** [comment]
Didn't know about ContiguousArray. But performance improvement is always great! I'm thinking that we can make ArrayDataProvider ask for a `Collection` instead. This way, users can use their own type of collection type how ever they want. What do you think?
