### ISSUE TITLE
Refresh control

### ISSUE THREAD

**Issue by hip4yes** [SoySauceLab/CollectionKit#44]
Thank you for a wonderful library! 
I was wondering what is the best way to add a refresh control at the top of CollectionView?

**Comment by Narsail** [comment]
As the CollectionView is based on the ScrollView you should be able to use the RefreshControl in the same way as with the UICollectionView or UITableView.

**Comment by Elshad** [comment]
`contentInset` of `collectionView` adds left margin to `refreshControl`
In `ArticleExampleViewController` it is 16 pixel

<img width="828" alt="screen shot 2018-01-19 at 17 05 33" src="https://user-images.githubusercontent.com/2334731/35152290-4a2b83d0-fd3b-11e7-8342-1a7bea19acd3.png">

**Comment by lkzhao** [comment]
@Elshad You can use layout inset instead of `contentInset`. try `layout = FlowLayout(lineSpacing: 30).inset(by: UIEdgeInsets(top: 20, left: 16, bottom: 20, right: 16))`, then remove the `contentInset`
