### ISSUE TITLE
Dynamic height in sizeProvider

### ISSUE THREAD

**Issue by bernhardwaidacher** [SoySauceLab/CollectionKit#45]
I have a view that consists of a label for a title, a label for a subtitle and a textfield. Since I don't know of the lenght of title + subtitle, it is possible for them to have multiple lines.
This is the view:

`
    import Foundation
    import UIKit

    class GenericSingleLineInputView: GenericView<String> {
    
    var viewModel: GenericSingleLineInputViewModel?

    private let title: UILabel = {
       let title = UILabel()
        title.font = Config.Font.text
        title.textColor = Config.Color.text
        title.backgroundColor = UIColor.red
        title.numberOfLines = 0
        return title
    }()
    
    private let subtitle: UILabel = {
        let title = UILabel()
        title.font = Config.Font.smallText
        title.textColor = Config.Color.text
        title.backgroundColor = UIColor.yellow
        title.numberOfLines = 0
        return title
    }()
    
    private let textfield: UITextField = {
       let textfield = UITextField()
        textfield.addTarget(self, action: #selector(inputValueChanged), for: .valueChanged)
        textfield.backgroundColor = UIColor.blue
        return textfield
    }()
    
    override func didLoad() {
        addSubview(title)
        addSubview(subtitle)
        addSubview(textfield)
        self.backgroundColor = UIColor.green
        title.snp.makeConstraints { (make) in
            make.top.equalTo(self).offset(12)
            make.left.equalTo(self)
            make.right.equalTo(self)
            make.bottom.equalTo(subtitle.snp.top)
        }
        
        subtitle.snp.makeConstraints { (make) in
            make.left.equalTo(self)
            make.right.equalTo(self)
            make.bottom.equalTo(textfield.snp.top)
        }
        
        textfield.snp.makeConstraints { (make) in
            make.height.equalTo(30)
            make.left.equalTo(self)
            make.right.equalTo(self)
            make.bottom.equalTo(self).offset(-12)
        }
    }
    
    @objc func inputValueChanged() {
        if let text = textfield.text {
            viewModel?.valueChanged(text)
        }
    }
    
    func setup(with viewModel: GenericSingleLineInputViewModel) {
        self.viewModel = viewModel
        title.text = viewModel.title
        subtitle.text = viewModel.subtitle
        textfield.text = viewModel.value
    }
}
`

Now I know to implement the sizeProvider property to set the size. I've tried it that way:

`        
let provider1 = CollectionProvider(dataProvider: CreateBudgetAddBudgetDataProvider(), viewProvider: CreateBudgetAddBudgetProvider())
        
        provider1.sizeProvider = {index, viewModel, size in
            let view = provider1.view(at: index)
            log.debug(view.sizeThatFits(CGSize(width: size.width, height: CGFloat.greatestFiniteMagnitude)))
            return CGSize(width: size.width, height: 100)
        }

        collectionView.provider = CollectionComposer(
            provider1
        )
`

However, this does not work, since 
`            
let view = provider1.view(at: index)
            log.debug(view.sizeThatFits(CGSize(width: size.width, height: CGFloat.greatestFiniteMagnitude)))
` 
will always return zero.

And this are the provider classes:
`
class CreateBudgetAddBudgetProvider: CollectionViewProvider<BudgetViewModel, UIView> {
    
    override func update(view: UIView, data: BudgetViewModel, index: Int) {
        if let view = view as? GenericSingleLineInputView, let viewModel = data as? GenericSingleLineInputViewModel {
            view.setup(with: viewModel)
        }
    }
    
    override func view(data: BudgetViewModel, index: Int) -> UIView {
        let view: UIView
        
        if data is GenericSingleLineInputViewModel {
            view = reuseManager.dequeue(GenericSingleLineInputView())
        }
        else {
            view = UIView()
        }
        update(view: view, data: data, index: index)
        
        return view
    }
    
    
}

class CreateBudgetAddBudgetDataProvider: CollectionDataProvider<BudgetViewModel> {
    var data: [BudgetViewModel] = []
    
    override init() {
        super.init()
        data.append(GenericSingleLineInputViewModel(title: "Name",valueChanged: { (value) in
            
        }, subtitle: "Hier könne Ihr name stehen"))
    }
    
    override var numberOfItems: Int {
        get {
            return data.count
        }
    }
    
    override func data(at: Int) -> BudgetViewModel {
        return data[at]
    }
}
`

edit: I'm sorry for the code formatting, can't get it to work 😅

**Comment by jindulys** [comment]
What is the view you get inside your `sizeProvider`?

`let view = provider1.view(at: index)`

Could you check its class?

If it is a `GenericSingleLineInputView`, could you check its title and subtitle's content?

Usually for sizeProvider, you'd better calculate size based on data instead of using view to do that.

**Comment by bernhardwaidacher** [comment]
> Usually for sizeProvider, you'd better calculate size based on data instead of using view to do that.

Thanks for that info. I have planned to do this, but thought maybe there is another way to solve this issue. Thank you!

**Comment by pteasima** [comment]
Thanks for making this library.

While I agree that basing the size off of data rather that autolayout is preferrable and more performant, I think that not having an "intrinsicSizeSizeProvider" or similar greatly limits the usefulness of the whole library. With how autolayout heavy iOS code usually is, this is a must have feature for me.

Below is an example of a simple tableView like layout with dynamic cell height:

```
@IBOutlet weak var collectionView: CollectionView!
    override func viewDidLoad() {
        super.viewDidLoad()
        let provider = CollectionProvider(data: ["firstfdshafhjkdajkhfdhkjfdahjhkgjfdaghdfagkhjadfghkjfdaghkjdfghjkakghjadfkghjfadghkjfdahjkgashjgkfdhjgkdfsahjgkdfashjgkfadsghjkfadhjgkhjgkfahjkgaf", "second"], viewUpdater: { (label: UILabel, data: String, index: Int) in
            label.numberOfLines = 0
            label.text = data
            label.backgroundColor = index == 0 ? .red : .green
        })
        provider.sizeProvider = { [unowned provider] (index,_, collectionSize) in
            let v = provider.view(at: index)
            return CGSize(
                width: collectionSize.width,
                height: v.systemLayoutSizeFitting(CGSize(width: collectionSize.width, height: UILayoutFittingCompressedSize.height)).height
            )
        }
        collectionView.provider = provider
    }
```

The problem with this approach is that you have to do the whole `[unowned]` dance and have to split the initialization into multiple steps. Similar code is bound to be repeated in many apps that use CollectionKit, but there arent good ways to simplify it.

Making this a feature of CollectionKit would be quite simple, but requires API breaking changes (at the very least, making the CollectionProvider or the View a parameter of the SizeProvider typealias). I might make a PR if I find the time, but first I wonder how the author feels about this and if they have any suggestions for how the new API should look (or any strong arguments against adding this feature).

**Comment by pteasima** [comment]
@bernhardwaidacher would you mind reopening the issue so that we can get a reaction? I dont wanna start a new issue since it follows the discussion here.

**Comment by lkzhao** [comment]
@pteasima 
Using AutoLayout for each cell greatly impact the performance of collection view. Because collection view can have thousands of cells, CollectionView only initializes views that are on screen. You don't want to create thousands of views for getting the sizes when there are only a few that is displayed. 

If we were to implement some way to use autolayout, we would be creating a dummy cell in the memory and use that to retrieve the size.

**Comment by pteasima** [comment]
@lkzhao Thanks for the reply. I agree that autolayout is slow but I dont quite get the "thousands of views" point. My sample code above seems to work even for large numbers of elements.

Is there a situation where CollectionKit asks for a size but the view hasnt been created and thus cannot be used for calculating size? This would make by solution from above impossible. I still have some ideas how to handle this but it would likely require bigger changes (and I would likely give up:))

**Comment by pteasima** [comment]
scratch that. I digged into the source and now I get your point. My confussion was that I didnt realize that provider.view(at:) actually constructs the view, I thought it will have been constructed and this is only a getter. Thanks for your time.

**Comment by pteasima** [comment]
@bernhardwaidacher with this new information, I discourage using my sample code from above. It really does create all views eagerly and the performance will be terrible.

**Comment by lkzhao** [comment]
@pteasima 
Try this maybe.
```swift
class ViewController: UIViewController {
  let dummyCell = YourView()
  let collectionView = CollectionView()
  override func viewDidLoad() {
    super.viewDidLoad()
    let viewUpdater = { (view: YourView, data: Int, index: Int) in
      view.backgroundColor = .red
      //...
    }
    collectionView.provider = CollectionProvider(
      data: [1],
      viewUpdater: viewUpdater,
      sizeProvider: { [dummyCell, viewUpdater] (index, data, maxSize) -> CGSize in
        viewUpdater(dummyCell, data, index) // first update the cell with current index's data
        return dummyCell.systemLayoutSizeFitting(maxSize)
      })
  }
}
```
keep in mind that performance of this won't be great for a lots of cells. 

There is also the `ViewCollectionProvider` class which is a special `CollectionProvider` that allows you to use existing views if you have them constructed already.

**Comment by pteasima** [comment]
Thanks, I didnt realize that CollectionKit needs to calculate all sizes upfront. I can still imagine it might be possible to only calculate sizes lazily. I think UITable/CollectionView do this somehow. It would involve constantly updating the contentSize as the user scrolls and new cell sizes get calculated. Updating the contentSize could mess up scrolling etc. While I think its doable (and I believe apple does this), its a hard problem and not one that can be solved without vast changes to the whole library. So, as I said, I give up and consider this matter closed ;)
