### ISSUE TITLE
WaterfallLayout can't set this layout?

### ISSUE THREAD

**Issue by michaeldong** [SoySauceLab/CollectionKit#49]
I set provider's layout with this code: 
`provider.layout = WaterfallLayout<UIImage>(columns: 2, spacing: 0.0)`
I set columns = 2, then I provide imagesize
 `func imageSizeProvider(at: Int, data: UIImage, collectionSize: CGSize) -> CGSize {

  if at == 0 {
    return CGSize(width: collectionSize.width, height: 150)
  }
  else if at == 1 {
    return CGSize(width: collectionSize.width/2, height: 150)
  }
  else {
    return CGSize(width: collectionSize.width/2, height: 150)
  }
}`

I want get this layout display ,

![image](https://user-images.githubusercontent.com/1925773/34485485-e8e4af94-f005-11e7-85e5-cb30505689b0.png)

I find this waterfalllayout, must demand equal width through set column = 2?

My question is, what's wrong I use, or has a better solution for this?

Thanks.

**Comment by lkzhao** [comment]
You can use flowlayout for this. WaterfallLayout currently only support fix number of columns. Or you can make 2 separate sections. section 1 with view 1 and the rest of the view in section 2 with a 2 column waterfall layout.

**Comment by michaeldong** [comment]
Thanks. 
I know this can solve my issue.
My example maybe  easy.
I have many views, those views equal width of screen or half. Height equal 300 or 150;  those size dynamic in Data models, so I  can't use flowlayout. 
Your suggestion use many separate sections is Good. But not Best, because I dynamic have items response from server, so this need me to controller use anyone section. 

I want to inherit your VerticalLayout, implement  my required layout ( equal screen width or half. height is equal a or a/2).  

Wish real WaterfallLayout. 

Thanks again for your CollectionKit and HERO!

**Comment by lkzhao** [comment]
@michaeldong Right, the current waterfall layout is pretty simple. I guess what you need is more of a masonry-like layout that allows cells to take up more than 1 column for different data value. I guess we can make it a part of the project as well.

**Comment by lkzhao** [comment]
Please reopen if you still need help. Thanks!
