### ISSUE TITLE
HorizontalGalleryViewController Not Reloading

### ISSUE THREAD

**Issue by GratePic** [SoySauceLab/CollectionKit#51]
I'm trying to update the HorizontalGalleryViewController in your examples, like ReloadDataViewController.

However, the view is not updating the new image.

I'm using the code below. 

//
//  HorizontalGalleryViewController.swift
//  CollectionKitExample
//
//  Created by Luke Zhao on 2016-06-14.
//  Copyright © 2016 lkzhao. All rights reserved.
//

import UIKit
import CollectionKit

func imageSizeProvider(at: Int, data: UIImage, collectionSize: CGSize) -> CGSize {
  var imageSize = data.size
  if imageSize.width > collectionSize.width {
    imageSize.height /= imageSize.width/collectionSize.width
    imageSize.width = collectionSize.width
  }
  if imageSize.height > collectionSize.height {
    imageSize.width /= imageSize.height/collectionSize.height
    imageSize.height = collectionSize.height
  }
  return imageSize
}

class HorizontalGalleryViewController: CollectionViewController {
  
  let addButton02: UIButton = {
    let button = UIButton()
    button.setTitle("+", for: .normal)
    button.titleLabel?.font = .boldSystemFont(ofSize: 20)
    button.backgroundColor = UIColor(hue: 0.6, saturation: 0.68, brightness: 0.98, alpha: 1)
    button.layer.shadowColor = UIColor.black.cgColor
    button.layer.shadowOffset = CGSize(width: 0, height: -12)
    button.layer.shadowRadius = 10
    button.layer.shadowOpacity = 0.1
    return button
  }()

  
  override func viewDidLoad() {
    super.viewDidLoad()
    addButton02.addTarget(self, action: #selector(add02), for: .touchUpInside)
    view.addSubview(addButton02)
    collectionView.contentInset = UIEdgeInsetsMake(10, 10, 10, 10)
    let provider = CollectionProvider(data: testImages, viewGenerator: { (data, index) -> UIImageView in
      let view = UIImageView()
      view.layer.cornerRadius = 5
      view.clipsToBounds = true
      return view
    }, viewUpdater: { (view: UIImageView, data: UIImage, at: Int) in
      view.image = data
    })
    provider.layout = WaterfallLayout<UIImage>(columns: 2).transposed()
    provider.sizeProvider = imageSizeProvider
    provider.presenter = WobblePresenter()
    self.provider = provider
  }
  
  override func viewDidLayoutSubviews() {
    super.viewDidLayoutSubviews()
    let viewWidth = view.bounds.width
    let viewHeight = view.bounds.height
    addButton02.frame = CGRect(x: 0, y: viewHeight - 44, width: viewWidth, height: 44)
    collectionView.frame = CGRect(x: 0, y: 0, width: viewWidth, height: viewHeight - 44)
  }
  
  @objc func add02() {
    let test =  UIImage(named: "6")!
    testImages.append(test)
    collectionView.reloadData()
    print(testImages)
  }

}

**Comment by lkzhao** [comment]
`testImages` is a different array from the one used in CollectionProvider.
Checkout the new README for v2.0.0 for more info.
