### ISSUE TITLE
Build error / Swiftlint

### ISSUE THREAD

**Issue by own2pwn** [SoySauceLab/CollectionKit#56]
Hi, I've [cloned](https://github.com/SoySauceLab/CollectionKit/commit/e5439f857df8bcee01daa3d54617543d4eaa6a4f) this commit and there're some build errors due to swiftlint. 

1. Sources/Layout/SimpleLayout.swift:12:3: error: Identifier Name Violation: Variable name should only contain alphanumeric characters: '_contentSize' (identifier_name)

2. /Sources/Addon/SpaceCollectionProvider.swift:20:3: error: Identifier Name Violation: Variable name should only contain alphanumeric characters: '_contentSize' (identifier_name)

**Comment by own2pwn** [comment]
#58

**Comment by lkzhao** [comment]
Should be fixed already, thanks for reporting.
