### ISSUE TITLE
Module isn't visible

### ISSUE THREAD

**Issue by own2pwn** [SoySauceLab/CollectionKit#57]
After building with carthage and linking framework, module still invisible in storyboard.
Am I doing smth. wrong?

**Comment by own2pwn** [comment]
Now I have auto-complete (I've selected class in SB with it), but looks like there's still error. 
<img width="1537" alt="default" src="https://user-images.githubusercontent.com/7850039/36901893-cc165e14-1e39-11e8-87eb-d5f9cb25cd53.png">

Framework is statically linked
<img width="552" alt="default" src="https://user-images.githubusercontent.com/7850039/36901936-eade3718-1e39-11e8-859b-02874a2d774e.png">

Also is it ok that I can't set CollectionView class to UICollectionView in SB? I can set it only for UIViews

**Comment by own2pwn** [comment]
This I'm getting after import CollectionKit in class

<img width="660" alt="default" src="https://user-images.githubusercontent.com/7850039/36902081-516c35ac-1e3a-11e8-9f7a-ca5ee269edd5.png">

**Comment by lkzhao** [comment]
CollectionView won't show up in storyboard. But you can drag a `View` object and change its class to `CollectionKit`.

Think you might already fixed the importing issues.

Please reopen if you still need help. Thanks!
