### ISSUE TITLE
AutoSize and Sticky headers questions

### ISSUE THREAD

**Issue by aCorrado** [SoySauceLab/CollectionKit#60]
Hi,
quick questions:
- are sticky headers (like section headers in UITableView) supported? will it be possible to write a customProvider for them?
- Is it possible to size the CollectionView based on the children size? Let's say that I want a collectionview as wide as the widest child, will be possible to achieve this result?

Thanks

**Comment by lkzhao** [comment]
Sticky header is coming in v2.0.

For your second feature request, I guess you can pre-calculate the width of the widest child and assign that width to the collectionView first.
