### ISSUE TITLE
Views that have wrong positionning

### ISSUE THREAD

**Issue by Malenea** [SoySauceLab/CollectionKit#62]
Hello,

So I'm pretty much new to swift and still learning a few things.
Tried to use the CollectionKit framework because it looked really nice.
I have an issue though, not too sure why, but I suppose I'm doing something wrong?

Trying to have a nice CollectionKit with UIButton so I mostly took back the code from the example and tweaked it to behave the way I want. The problem is that the UIViews are weirdly positioned.

Would any of you have any idea on the why?

Here is my code:

```swift
func sizeProvider(at: Int, data: UIButton, collectionSize: CGSize) -> CGSize {
    var size = data.frame.size
    if size.width > collectionSize.width {
        size.height /= size.width / collectionSize.width
        size.width = collectionSize.width
    }
    if size.height > collectionSize.height {
        size.width /= size.height / collectionSize.height
        size.height = collectionSize.height
    }
    return size
}

class GenericCollectionView {
    class func createForButton(frame: CGRect, buttons: [UIButton]) -> CollectionView {
        let collectionView = CollectionView(frame: frame)
        collectionView.contentInset = UIEdgeInsetsMake(10, 10, 10, 10)
        let provider = CollectionProvider(
            data: buttons,
            viewUpdater: { (view: UIView, data: UIButton, index: Int) in
                view.addSubview(data)
        })

        let visibleFrameInsets = UIEdgeInsets(top: 0, left: -100, bottom: 0, right: -100)
        provider.layout = WaterfallLayout<UIButton>(columns: 2).transposed().insetVisibleFrame(by: visibleFrameInsets)
        provider.sizeProvider = sizeProvider
        collectionView.provider = provider
        return collectionView
    }
}
```

collectionView is screen's height / 2 and placed in the centre.
And here is what it looks like, the views are like off-centred:

<img width="383" alt="screen shot 2018-04-12 at 17 35 22" src="https://user-images.githubusercontent.com/13222548/38691408-b00229a6-3e78-11e8-97e4-ba049ffbf69a.png">

Oh and on a sidenote the buttons are not clickable.

**Comment by lkzhao** [comment]
Given that you already have a list of buttons. You can use `ViewCollectionProvider` which is already a generic collection provider given a list of view.

```swift
collectionView.provider = ViewCollectionProvider(views: buttons, layout: WaterfallLayout(columns: 2).transposed())
```

**Comment by lkzhao** [comment]
Note that CollectionView is intended to map a long list of data to views. 
Views are created and managed by CollectionKit, and won't be created if it is outside of the screen.
It is usually not efficient to create all the buttons in a collectionView upfront as it waste memory and time to create them.

To make you button clickable. You can use UIButton's [addTarget(_:action:for:)](https://developer.apple.com/documentation/uikit/uicontrol/1618259-addtarget) method.

But from what I can see, you don't really need UIButton as you are not using any or its behavior. You can use a custom UIView or UIImageView instead. and add a tapHandler to the CollectionProvider.

**Comment by Malenea** [comment]
True that, thanks for the help.
