### ISSUE TITLE
DidSelectItem

### ISSUE THREAD

**Issue by glur4k** [SoySauceLab/CollectionKit#65]
Hi,

is there a way to detect when an item is selected?
Like in collectionView didSelectItemAtIndexPath etc.?

Greetings

**Comment by lkzhao** [comment]
Not supported at the moment. don't want to overload too many features into CollectionView. But it is very easy to build this feature in your project with CollectionKit. Just keep a selected sets in your view controller. then assign a tapHandler and update that selected sets. Every time the selected sets changes, call `collectionView.setNeedsReload()`. Finally in the `viewUpdater` function, update your views to indicate selected/unselected state.

I have done this many times and it should be easy to do so. If time permits, I will add a new examples in the example project later after I release v2.0.

**Comment by LinusGeffarth** [comment]
Wait, we cannot do anything when a cell is selected? That makes this unusable, unfortunately...who has a collection view that doesn't allow the user to tap cells?!
I really like the code examples, so I'd be happy to use the library if it featured this. I don't feel like cell selection can be considered *overloading too many features*.
