### ISSUE TITLE
i can't use ‘WobblePresenter’  when i install by CocoaPods

### ISSUE THREAD

**Issue by EdLiya** [SoySauceLab/CollectionKit#67]

**Comment by EdLiya** [comment]
![image](https://user-images.githubusercontent.com/15958795/41329177-a58728e4-6efe-11e8-94ac-8d0f162faa07.png)

**Comment by lkzhao** [comment]
WobblePresenter is not shipped with CollectionKit itself. but feel free to grab it from the Example project.
