### ISSUE TITLE
How could I set a select or tap style for cell or any interactionable style

### ISSUE THREAD

**Issue by wakaryry** [SoySauceLab/CollectionKit#72]
Thanks for the wonderful framework! 
How could I add any selection style?

It seems to have no interaction style for select or tap.
Even when I used a UIButton in my viewsource, it has no state change style interaction.
How could I use it to enable the default button click interaction style?

How could I make a background color or shadow change when I click the cell or any style change when I click a UIControl?

**Comment by wakaryry** [comment]
The tap effect in UIControl can not show when just a quick tap. The tap event is triggered.
When hold the tap for a second, it could show the tap effect.

**Comment by wakaryry** [comment]
It seems the CollectionView eats the tap effect.
In the example's `DynamicView`, the dynamic effect is quite sensitive when used out of a `CollectionView`.
But when used in `CollectionView`, I can not see the dynamic effect with tap. The effect will show when we hold the tap for a more time. It becomes very dull.

**Comment by lkzhao** [comment]
This is a UIScrollView side effect.

Set delayContentTouches to false

**Comment by lkzhao** [comment]
You might also need to set delayTouchesBegan to false on CollectionView’s tapGestureRecognizer

**Comment by wakaryry** [comment]
Got it. 
Thanks.
OK for tap now. 

```swift
self.collectionView.tapGestureRecognizer.delaysTouchesBegan = false
self.collectionView.delaysContentTouches = false
```

Will it have some side affect?

**Comment by wakaryry** [comment]
The scrollView's scroll action was affected. 
I reuse the default now.
And add animations for the view need an animation interaction.
