### ISSUE TITLE
any way to use with Realm's Results<T> for dataSource?

### ISSUE THREAD

**Issue by wakaryry** [SoySauceLab/CollectionKit#76]
I am using [Realm](https://github.com/realm/realm-cocoa) for my local db.

Any way to use Realm's Results<T> for dataSource?

Not to change Results<T> list to a swift Array.

**Comment by wakaryry** [comment]
Now I use it in this way:
> I maintain both Realm's Results<T> list and swift's Array<T> array.
> Results<T> is for the connection of Realm db, and I listen to Results<T>.
> If any change in Results<T>, I will sync the change into Array<T>.

**Comment by wakaryry** [comment]
But the problem is `Results<T>` is lazy loaded and is not sliced into pieces. It always means the whole data of type T in the db. If the result is large, I think it's expensive to map it into an swift array.
Any suggestions?
Thanks.

**Comment by lkzhao** [comment]
For now you can create your own dataSource that use `Results<T>`

just subclass `DataSource<T>` and override the following methods. Shouldn't be hard.
```swift
  open var numberOfItems: Int {
    return 0
  }
  open func data(at: Int) -> Data {
    fatalError()
  }
  open func identifier(at: Int) -> String {
    return "\(at)"
  }
```

**Comment by wakaryry** [comment]
Thanks for the reply. 

Solution:
```swift
import Foundation
import RealmSwift
import CollectionKit

class RealmDataSource <T>: DataSource<T> where T:Object {
    var results: Results<T>
    
    init(data: Results<T>) {
        self.results = data
        super.init()
    }
    
    override open var numberOfItems: Int {
        return self.results.count
    }
    
    open override func data(at: Int) -> T {
        return self.results[at]
    }
    
    override open func identifier(at: Int) -> String {
        return "\(at)"
    }
}
```

Usage: Just replace the DataSource with RealmDataSource.
`dataSource: RealmDataSource(data: self.albums!)`

The whole provider:
```swift
var albums: Results<AlbumModel>?

let albumProvider = BasicProvider(
            identifier: nil,
            dataSource: RealmDataSource(data: self.albums!),
            viewSource: ClosureViewSource(viewGenerator: { (_, index) -> AlbumTableCell in
                return AlbumTableCell.loadFromNib(named: "AlbumTableCell", bundle: nil) as! AlbumTableCell
            }, viewUpdater: { (albumV: AlbumTableCell, _, index) in
                albumV.backgroundColor = .white
            }),
            sizeSource: { (index, _, _) -> CGSize in
                return CGSize(width: self.view.bounds.width, height: 260)
        },
            layout: FlowLayout(lineSpacing: onePixalLineHeight),
            animator: nil,
            tapHandler: { (tapContext) in
                
        })
```
