### ISSUE TITLE
Remove and add animation doesn't work

### ISSUE THREAD

**Issue by Banck** [SoySauceLab/CollectionKit#79]
Hello!
Don't understand why, but in your example when cell is adding or removing we can see the animation properly, but in my project removing the latest cell, even if I call removeFirst() :
```
collectionView.provider = BasicProvider(
            dataSource: dataSource,
            viewSource: ClosureViewSource(viewGenerator: { (data, index) -> UILabel in
                let cell = UILabel()
                cell.text = data.name
                cell.backgroundColor = .yellow
                return cell
            }, viewUpdater: { (view: UILabel, data: Match, at: Int) in
                view.text = data.name
            }),
            sizeSource: sizeSource,
            layout:  FlowLayout(lineSpacing: 10,justifyContent: .center),
            animator: WobbleAnimator(),
            tapHandler: { [weak self] context in
                self?.dataSource.data.remove(at: context.index)
            }
        )

```
Video:
http://dropmefiles.com/KrXuP

**Comment by lkzhao** [comment]
WobbleAnimator doesn’t have insert or delete animation built in

**Comment by lkzhao** [comment]
You can subclass WobbleAnimator and copy the code from AnimatedReloadAnimator to have both insert delete wobble animations.

**Comment by Banck** [comment]
@lkzhao Hey!
My WobbleAnimator is like: https://gist.github.com/Banck/0d2981d4ed50d9f8820411c70d94c33e
And in your example I replaced with this one and it works..

**Comment by Banck** [comment]
And As you can see in the video, if I scroll to the end and try to remove the latest cell - animations works. If I tried to remove latest - 1 or -2 animation is apply to the latest one.

**Comment by lkzhao** [comment]
@Banck Did you provide different identifier for individual items?

**Comment by lkzhao** [comment]
Otherwise it is not clear to CollectionKit that you removed a particular cell.

**Comment by Banck** [comment]
@lkzhao  no, I didn't.
But now I tried to initialize my dataSource with identifierMapper and return id of my model and it works!
Thanks :-)

**Comment by Banck** [comment]
@lkzhao But animation seems doens't apply to the lower cells. See the video:
https://dropmefiles.com/QckrT

**Comment by lkzhao** [comment]
It is because the lower cells just came on screen and your WobbleAnimator doesn't do any insert animation.
