### ISSUE TITLE
3D cascading animator

### ISSUE THREAD

**Issue by lyptt** [SoySauceLab/CollectionKit#82]
Is there an example of how to achieve the 3D cascading animator shown in the readme? It looks like exactly what I need!

**Comment by brightfuture** [comment]
It's included in the example project, find `EdgeShrinkAnimator`

**Comment by lyptt** [comment]
You mean this one? I've tried using EdgeShrinkAnimator and replacing the data with a new array and it just pops in instantly.

![](https://camo.githubusercontent.com/ecfdd5cc41e5b726eb650a097ec7d3f1e8556e05/687474703a2f2f6c6b7a68616f2e636f6d2f7075626c69632f706f7374732f636f6c6c656374696f6e4b69742f72656c6f6164416e696d6174696f6e2e676966)

**Comment by brightfuture** [comment]
You are probably changing the data the wrong way, do it like this: dataProvider.data = aNewArray

**Comment by lyptt** [comment]
That's exactly what I'm doing

**Comment by lkzhao** [comment]
@lyptt This is an example inside the example project. the animator is also included in the example.
