### ISSUE TITLE
Best way to add gesture recognizer to each element? 

### ISSUE THREAD

**Issue by tangert** [SoySauceLab/CollectionKit#84]
For example, I want to make a collection view of buttons. Just wondering what the best way to go about this is with this library.

**Comment by lkzhao** [comment]
3 ways:

1. use BasicProvider's tapHandler to handle tap action
2. Delegate Pattern, create a custom button subclass. each button should handle touch or add its own gesture recognizer. Assign your view controller as the delegate of each button inside the viewUpdater. then when button detects the touch, drag, etc.. call the delegate's method along with the necessary information.
3. closure callback, in your custom button subclass, store an optional closure. and inside the viewUpdater, assign the closure from your view controller for specific actions. For example, you can have an `var onTap: ((Button) -> Void)?` stored inside your button. and in your viewUpdater
```swift
button.onTap = { [weak self] button in
  self?.handleTap(button: button)
}
```

**Comment by snc001** [comment]
how do you use tapHandler??
