### ISSUE TITLE
DataSource of any type?

### ISSUE THREAD

**Issue by JamesirYao** [SoySauceLab/CollectionKit#91]
let deviceProvider = BasicProvider(
            dataSource: ArrayDataSource(data: deviceEntities),
            ...
)

where deviceEntities is a list of some CoreData entities. When I do this, the compiler said Cannot convert value of type '[CoreDataDevice]' to expected argument type '[_]'. 

Does it only support String and Int type?

**Comment by lkzhao** [comment]
It should support CoreDataDevice. check your viewSource to see if there is a data type mismatch

**Comment by doronkatz** [comment]
I am getting this error too now across the board with examples. Has the examples been tested with Swift 4.2?
