### ISSUE TITLE
Reuse cells

### ISSUE THREAD

**Issue by Banck** [SoySauceLab/CollectionKit#97]
Hello!
When user scroll every cell are creating again. My cells creating from xib, so it too expensive to create every cells again when scroll.
Is there any built-in layout or something else, so my cells will reuse, not create again?
Thanks!

**Comment by lkzhao** [comment]
CollectionKit does reuse cells. but when the user first started scrolling, there will be no cell to reuse, so a few cells might be created fresh. 

CollectionKit also dumps cells in memory after 0.5s to save memory. But you can set ViewSource's reuseManager's lifeSpan to be a very large time interval to disable this behaviour.

Checkout the following: CollectionViewReuseManager.lifeSpac, ViewSource.reuseManager

**Comment by Banck** [comment]
@lkzhao Hello!
Thank you for your help.
Very strange... I have project with carthage, version of CollectionKit is 2.1.0.
With simple provider:
      ```
 let cellUpdater = { (cell: MatchCell, data: Match, at: Int) in
            cell.configure(with: data)
        }
        
        let viewGenerator = { (data: Match, index: Int) -> MatchCell in
            let cell = MatchCell()
            print("view generated at index \(index)")
            return cell
        }

        let sourceView = ClosureViewSource(viewGenerator: viewGenerator, viewUpdater: cellUpdater)
        sourceView.reuseManager.lifeSpan = 60 * 10
        
        let sourceSize = { (index: Int, data: Match, collectionSize: CGSize) -> CGSize in
                return CGSize(width: collectionSize.width, height: 220)
        }
        
        super.init(
            dataSource: dataSource,
            viewSource: sourceView,
            sizeSource: sourceSize,
            layout:  FlowLayout(lineSpacing: 17).inset(by: UIEdgeInsets(top: 0, left: 6, bottom: 0, right: 6)),
            animator: WobbleAnimator(),
            tapHandler: tapHandler
        )
    }
```
and  sourceView.reuseManager.lifeSpan = 60 * 10 doesn't do anything. In the log when I scroll I can see that all cells are creating again and again...:
![image](https://user-images.githubusercontent.com/6259254/45621642-3ff51380-baab-11e8-9c64-995138cfc17e.png)

But I have another project with cocoapods and everything ok. Provider like previous , without using sourceView.reuseManager.lifeSpan... don't know what can be reason....

**Comment by Banck** [comment]
And in the second project, where cell does reuse, on older devices like iPhone 5 (iOS 10.3) and iPhone 6 (iOS 11-12) when scroll fps are drop....

**Comment by Banck** [comment]
Here is log from Time profiler:
![image](https://user-images.githubusercontent.com/6259254/45752047-74e59f80-bc3e-11e8-8247-8ab614070a12.png)
Here is my provider:

```
let viewGenerator = { (data: Product, index: Int) -> ItemGridCell in
            let cell = ItemGridCell()
            print("view generated at index \(index)")
            return cell
        }

        let cellUpdater = { (cell: ItemGridCell, data: Product, at: Int) in
            cell.configure(with: data)
            cell.didSelectAddToCart = {
                addToCartAction?(data, at)
            }
            cell.didSelectRemoveFromCart = {
                removeFromCartAction?(data, at)
            }
        }
        
        let viewSource = ClosureViewSource(viewGenerator: viewGenerator, viewUpdater: cellUpdater)
        let sizeSource = { (index: Int, data: Product, collectionSize: CGSize) -> CGSize in
            let width = (collectionSize.width - 14 * 2) / 3 
            return CGSize(width: width, height: 170)
        }
        
        super.init(
            dataSource: dataSource,
            viewSource: viewSource,
            sizeSource: sizeSource,
            layout: FlowLayout(lineSpacing: 48, interitemSpacing: CGFloat(14).dp).inset(by: UIEdgeInsets(top: 16, left: CGFloat(16).dp, bottom: 16, right:  CGFloat(16).dp))
            animator: AnimatedReloadAnimator()
        )
```

**Comment by Banck** [comment]
@lkzhao as can I see, the issue in performace, that when scroll previous cell is removing from superview and then do addSubview. Maybe you don't need to do removeFromSuperview/addSubview but just change position? Changing the position of cell is much less expensive than removing/adding.
@lkzhao What do you mean?
Thanks!

**Comment by lkzhao** [comment]
@Banck It might be a good idea to not remove the view from CollectionView and just hide it. I will experiment with that.

About the Carthage release, I will double check. it might be that class naming is different in Carthage build.

**Comment by lkzhao** [comment]
Hey @Banck, can you test out `perf-test` branch to see if it fix the performance issue you are having.

**Comment by lkzhao** [comment]
@Banck I also checked myself with Carthage. and it cell reuse worked ok for me.

Here is my code used for the test:
```swift
import UIKit
import CollectionKit

class ViewController: UIViewController {
  let collectionView = CollectionView()

  override func viewDidLoad() {
    super.viewDidLoad()

    view.addSubview(collectionView)

    collectionView.provider = BasicProvider(
      dataSource: ArrayDataSource(data: Array(0..<100)),
      viewSource: ClosureViewSource(
        viewGenerator: { (data, index) -> UILabel in
          print("view generated at \(index)")
          return UILabel()
        },
        viewUpdater: { (cell: UILabel, data, index) in
          cell.text = "\(data)"
      }),
      sizeSource: { index, data, collectionSize in
        // 2. return size for each StoryItemCell here
        return CGSize(width: 100, height: 100)
    })
  }

  override func viewDidLayoutSubviews() {
    super.viewDidLayoutSubviews()
    collectionView.frame = view.bounds
  }

}
```

and scrolling from bottom to the top only generated 4 cells.

```
view generated at 60
view generated at 61
view generated at 62
view generated at 63
```

**Comment by Banck** [comment]
Hello, @lkzhao !
I’ve tested and now scroll has become much smoother!  Thanks for fixing it. Awesome 👏 
But there is 1 more issue: when we start to scroll new cell will be created and there can be some freeze, if cell is so complex. Maybe collectionkit should create all visible cells + n more cell, which will be next?

**Comment by lkzhao** [comment]
@Banck Does that happen with any other animators?

**Comment by Banck** [comment]
Sorry, with Wobble all is fine. Only with AnimatedReloadAnimator.

**Comment by lkzhao** [comment]
Weird, it doesn't happen for me with AnimatedReloadAnimator

**Comment by Banck** [comment]
Hm...Do you test from carthage build? 
Animator from this code: https://github.com/SoySauceLab/CollectionKit/blob/39650b0fa2ce5bc96272d714633f37e92d6af66b/Examples/CollectionKitExamples/ReloadAnimationExample/ReloadAnimationViewController.swift

**Comment by lkzhao** [comment]
Yes, I am using carthage and this animator.

Here is the project: https://github.com/lkzhao/CollectionKitCarthageTest

I've added you to the project. Try to see if you can reproduce it in this project.

**Comment by Banck** [comment]
Hm...really strange..can't reproduce, tried with different ways, but nothing... don't know why in my project have this issue.. Will. try to find out the reason, and will let you know. 
Thanks a lot for your help!

**Comment by Banck** [comment]
@lkzhao, Hey!
I've fixed issue with reuse. I had file UIView+CollectionKit.swift in my project with this code:

```
extension UIView {
    private struct AssociatedKeys {
        static var reuseManager = "reuseManager"
        static var animator = "animator"
        static var currentAnimator = "currentAnimator"
    }
    
    internal var reuseManager: CollectionReuseViewManager? {
        get { return objc_getAssociatedObject(self, &AssociatedKeys.reuseManager) as? CollectionReuseViewManager }
        set { objc_setAssociatedObject(self, &AssociatedKeys.reuseManager, newValue, .OBJC_ASSOCIATION_RETAIN_NONATOMIC) }
    }
    
    public var collectionAnimator: Animator? {
        get { return objc_getAssociatedObject(self, &AssociatedKeys.animator) as? Animator }
        set {
            if collectionAnimator === currentCollectionAnimator {
                currentCollectionAnimator = newValue
            }
            objc_setAssociatedObject(self, &AssociatedKeys.animator, newValue, .OBJC_ASSOCIATION_RETAIN_NONATOMIC)
        }
    }
    
    internal var currentCollectionAnimator: Animator? {
        get { return objc_getAssociatedObject(self, &AssociatedKeys.currentAnimator) as? Animator }
        set { objc_setAssociatedObject(self, &AssociatedKeys.currentAnimator,
                                       newValue, .OBJC_ASSOCIATION_RETAIN_NONATOMIC) }
    }
    
    public func recycleForCollectionKitReuse() {
        removeFromSuperview()
        reuseManager?.queue(view: self)
    }
    
}
```
Seems this code is out of date and that's why my cells don't reuse. I've removed it and now all if fine. Don't know why I had this, but...thanks :-)
